apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mbarbisanazchcaptureorder 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mbarbisanazchcaptureorder 
    spec:
      containers:
        - name: mbarbisanazchcaptureorder 
          image: rtest1.azurecr.io/mbarbisanazchcaptureorder
          ports:
          - containerPort: 8080